version: '3.2'

networks:
    app_network:
        external:
            name: app_network

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        hostname: prometheus
        volumes:
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        links:
            - cadvisor:cadvisor
        depends_on:
            - cadvisor
        restart: always
        networks: 
            - app_network
            
    node-exporter:
        container_name: node-exporter
        hostname: node-exporter
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - 9100:9100
        restart: always
        networks:
            - app_network

    grafana:
        container_name: grafana
        hostname: grafana
        image: grafana/grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - ./grafana:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=3w3khei7jy
        restart: always
        networks: 
            - app_network
        
    cadvisor:
        container_name: cadvisor
        hostname: cadvisor
        image: google/cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        ports:
            - 8081:8080
        restart: always
        networks:
            - app_network

    # alertmanager:
    #     image: prom/alertmanager
    #     ports:
    #         - 9093:9093
    #     volumes:
    #         - ./alertmanager/:/etc/alertmanager/
    #     restart: always
    #     command:
    #         - --config.file=/etc/alertmanager/config.yml
    #         - --storage.path=/alertmanager
    # alertmanager-bot:
    #     image: metalmatze/alertmanager-bot:0.3.1
    #     environment:
    #         - ALERTMANAGER_URL=http://<alertmngerURL>:9093 #откуда бот получает алерт
    #         - LISTEN_ADDR=0.0.0.0:8080
    #         - BOLT_PATH=/data/bot.db
    #         - STORE=bolt
    #         - TELEGRAM_ADMIN=<TelegramAdminID> #ваш ID в телеграм
    #         - TELEGRAM_TOKEN=<TelegramBotToken> # токен бота
    #         - TEMPLATE_PATHS=/templates/default.tmpl
    #     volumes:
    #         - /srv/monitoring/alertmanager-bot:/data
    #     ports:
    #         - 8080:8080
